name: Daily Market Update

on:
  schedule:
    - cron: '0 21 * * 1-5'  # 9 PM UTC, Monday-Friday (after US market close)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate new index.html
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Daily Market Updates</title>
          </head>
          <body>
              <h1>Market Update</h1>
              <p>Date: $(date +"%A, %B %d, %Y")</p>
              <p>Generated: $(date +"%I:%M %p %Z")</p>
              <!-- Add your market content here -->
          </body>
          </html>
          EOF
      
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Market update: $(date +%Y-%m-%d)" && git push)
